# Generated by Django 4.2.7 on 2023-11-22 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_remove_post_likes_remove_post_save_post_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='user_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='save',
            field=models.ManyToManyField(blank=True, related_name='user_save', to=settings.AUTH_USER_MODEL),
        ),
    ]
