# Generated by Django 4.2.7 on 2023-11-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_post_likes_alter_post_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='save',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
