# Generated by Django 4.2.7 on 2023-11-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Url',
        ),
        migrations.AddField(
            model_name='post',
            name='short_link',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
