# Generated by Django 4.2.7 on 2023-11-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_alter_comment_reply_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='point',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
    ]
