# Generated by Django 4.2.7 on 2023-11-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_user_postition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='postition',
            new_name='position',
        ),
    ]
