# Generated by Django 4.2.7 on 2023-11-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_rename_postition_user_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='position',
            new_name='postition',
        ),
    ]
