# Generated by Django 4.2.7 on 2023-11-27 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_rename_position_user_postition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='postition',
            new_name='position',
        ),
    ]
