# Generated by Django 4.2.7 on 2023-12-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_alter_comment_post_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
