# Generated by Django 4.2.7 on 2023-12-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0016_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
    ]
