# Generated by Django 4.2.7 on 2023-12-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0018_category_author_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='users_profile/'),
        ),
    ]
