# Generated by Django 4.2.7 on 2023-12-22 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0022_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
