# Generated by Django 4.2.7 on 2023-12-24 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0023_remove_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Bug', 'Bug'), ('Proposal', 'Proposal'), ('Support', 'Support'), ('Criticism', 'Criticism')], default='Support', max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(max_length=1000)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='blog_app.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['-created'], name='blog_app_ti_created_956f42_idx')],
            },
        ),
    ]
