# Generated by Django 4.2.7 on 2023-12-24 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0024_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='blog_app.ticket'),
        ),
    ]
