# Generated by Django 4.2.7 on 2023-12-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0028_room_creator'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='blog_app_me_created_d493ae_idx',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created'], name='blog_app_me_created_f79cfd_idx'),
        ),
    ]
