# Generated by Django 4.2.7 on 2023-12-27 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0029_remove_message_blog_app_me_created_d493ae_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created',)},
        ),
        migrations.RemoveField(
            model_name='post',
            name='short_link',
        ),
    ]
