# Generated by Django 4.2.7 on 2023-12-30 09:41

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0030_alter_message_options_remove_post_short_link'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='room',
            managers=[
                ('opens', django.db.models.manager.Manager()),
            ],
        ),
    ]
